name: Keep Supabase Alive

on:
  push:   # 👈 AJOUTE ÇA
    branches:
      - master
  schedule:
    - cron: "0 3 */2 * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase
        run: |
          curl -X GET "https://cwalwgecwugfmixxjtgb.supabase.co/rest/v1/" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}"